# Generated by Django 4.0.6 on 2022-07-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=50)),
                ('iata', models.CharField(max_length=50)),
                ('icao', models.CharField(max_length=50)),
                ('airport_arrival', models.CharField(max_length=50)),
                ('iata_arrival', models.CharField(max_length=50)),
                ('scheduled_arrival', models.DateTimeField()),
                ('airport_departure', models.CharField(max_length=50)),
                ('iata_departure', models.CharField(max_length=50)),
                ('scheduled_departure', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Apartado',
        ),
    ]
